# Generated by Django 4.2.4 on 2023-09-26 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_title_post_tittle"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="tittle",
            new_name="title",
        ),
    ]
